## Задание 1.3.1

In [46]:
import numpy as np
arr = np.zeros(8*8).reshape(8, 8)
arr[::2, ::2] += np.ones(4)
arr[1::2, 1::2] += np.ones(4)
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


## Задание 1.3.2

In [67]:
arr = np.arange(5*5).reshape(5, 5)
for i in range(0, 5):
    arr[i] = np.arange(5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## Задание 1.3.3

In [68]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.26041094 0.05307374 0.3233831 ]
  [0.21673484 0.34191368 0.37982688]
  [0.5596488  0.07791364 0.50781239]]

 [[0.12372471 0.31193327 0.17157801]
  [0.4850874  0.49368175 0.28658908]
  [0.98428291 0.21803274 0.2131813 ]]

 [[0.52770556 0.85430971 0.88352738]
  [0.51585343 0.75274836 0.57593197]
  [0.38775553 0.84230367 0.11706459]]]


## Задание 1.3.4

In [61]:
size1 = int(input("Enter first matrix size:"))
size2 = int(input("Enter second matrix size:"))
arr = np.ones(size1*size2).reshape(size1, size2)
arr[1:size1-1:1, 1:size2-1:1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Задание 1.3.5

In [70]:
size = int(input("Enter array size:"))
arr = np.random.random(size)
arr[::-1].sort()
print(arr)

[0.9874225  0.84290518 0.80880816 0.80595994 0.73234506 0.67620821
 0.6383582  0.60893164 0.52561612 0.46495978 0.41896491 0.35062341
 0.33833673 0.28162045 0.23201063 0.21245389 0.1977669  0.14479533
 0.14035754 0.06313219]


## Задание 1.3.6

In [71]:
size1 = int(input("Enter first matrix size:"))
size2 = int(input("Enter second matrix size:"))
arr = np.arange(size1*size2).reshape(size1, size2)
print("matrix form", arr.shape)
print("matrix size", arr.size)
print("matrix amount of dims element", arr.ndim)

matrix form (10, 12)
matrix size 120
matrix amount of dims element 2


## Задание 2.3.1

In [72]:
import pandas as pd
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])
sum((a - b)**2)**.5

2.0

## Задание 2.3.2

In [81]:
## I masked path, so no one can one my own home pc path
df = pd.read_csv("baseball.csv")
df

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
0    0.271  0.328   74  161  22  6  12   58  49  133  23  17   1   1   0   0   
1    0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2    0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3    0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   
4    0.206  0.262   14   51  18  1   1   28  17   26   0   3   1   1   0   0   
..     ...    ...  ...  ...  .. ..  ..  ...  ..  ...  ..  ..  ..  ..  ..  ..   
332  0.269  0.303   32   58  12  1  13   33  11   51   1   2   0   0   0   0   
333  0.288  0.366   24   47   7  0   7   24  18   23   2   3   0   0   0   0   
334  0.208  0.265   12   35  11  1   0   15  14   30   2   6   0   0   0   0   
335  0.290  0.349   59  141  30  2  16   64  42  102  14   6   1   0   0   0   
336  0.225  0.312   37   64  12  0  17   48  36   80   1   0   1   0   0   0   

     salary  
0       109  
1       160  
2      2700  
3       550  
4       300  
..      ...  
332     140  
333     525  
334     365  
335     990  
336    2167  

[337 rows x 17 columns]

## Задание 2.3.3

In [74]:
df.head(2)

1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
0  0.271  0.328  74  161  22  6  12  58  49  133  23  17   1   1   0   0   
1  0.264  0.318  24   48   7  0   1  22  15   18   0   7   0   0   0   0   

   salary  
0     109  
1     160

In [75]:
df.tail(3)

1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
334  0.208  0.265  12   35  11  1   0  15  14   30   2   6   0   0   0   0   
335  0.290  0.349  59  141  30  2  16  64  42  102  14   6   1   0   0   0   
336  0.225  0.312  37   64  12  0  17  48  36   80   1   0   1   0   0   0   

     salary  
334     365  
335     990  
336    2167

In [76]:
df.shape

(337, 17)

In [77]:
df.describe()

1           2           3           4           5           6  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     0.257825    0.323973   46.697329   92.833828   16.673591    2.338279   
std      0.039546    0.047132   29.020166   51.896322   10.452001    2.543336   
min      0.063000    0.063000    0.000000    1.000000    0.000000    0.000000   
25%      0.238000    0.297000   22.000000   51.000000    9.000000    0.000000   
50%      0.260000    0.323000   41.000000   91.000000   15.000000    2.000000   
75%      0.281000    0.354000   69.000000  136.000000   23.000000    3.000000   
max      0.457000    0.486000  133.000000  216.000000   49.000000   15.000000   

                7           8           9          10          11          12  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     9.097923   44.020772   35.017804   56.706231    8.246291    6.771513   
std      9.289934   29.559406   24.842474   33.828784   11.664782    5.927490   
min      0.000000    0.000000    0.000000    1.000000    0.000000    0.000000   
25%      2.000000   21.000000   15.000000   31.000000    1.000000    3.000000   
50%      6.000000   39.000000   30.000000   49.000000    4.000000    5.000000   
75%     15.000000   66.000000   49.000000   78.000000   11.000000    9.000000   
max     44.000000  133.000000  138.000000  175.000000   76.000000   31.000000   

               13          14          15          16       salary  
count  337.000000  337.000000  337.000000  337.000000   337.000000  
mean     0.397626    0.115727    0.192878    0.029674  1248.528190  
std      0.490135    0.320373    0.395145    0.169938  1240.013309  
min      0.000000    0.000000    0.000000    0.000000   109.000000  
25%      0.000000    0.000000    0.000000    0.000000   230.000000  
50%      0.000000    0.000000    0.000000    0.000000   740.000000  
75%      1.000000    0.000000    0.000000    0.000000  2150.000000  
max      1.000000    1.000000    1.000000    1.000000  6100.000000

In [78]:
df.iloc[1:4]

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
1  0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2  0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3  0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   

   salary  
1     160  
2    2700  
3     550

In [79]:
df[df['salary'] > 1248].head(5)

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
2   0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
9   0.266  0.359  115  152  32  1  44  122  78  152  26   9   1   0   0   0   
10  0.235  0.353   39   67  10  0  11   33  48   92  14   3   1   0   0   0   
11  0.262  0.312   45  116  25  3   4   41  26   55  11   5   0   0   1   0   
13  0.285  0.380   96  157  30  3   3   50  83   36  35   8   1   0   0   0   

    salary  
2     2700  
9     4300  
10    3600  
11    1650  
13    2000

## Задание 3.3.2

In [80]:
from sklearn import preprocessing
## I masked path, so no one can one my own home pc path
df = pd.read_csv("iris.csv")
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_sepal_length = minmax_scaler.fit_transform(df[['sepal_length_cm']])
df.sepal_length_cm = scaled_sepal_length
standart_scaler = preprocessing.StandardScaler()
scaled_sepal_width = standart_scaler.fit_transform(df[['sepal_width_cm']])
df.sepal_width_cm = scaled_sepal_width
df

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]